version: '3.8'

services:
  postgres-hypha:
    image: postgres
    container_name: postgres-hypha
    environment:
      POSTGRES_DB: hypha
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    networks:
      - hypha-network

  hypha-api:
    build:
      context: ..
      dockerfile: Dockerfile
    image: hypha-api:${TAG:-latest}
    container_name: hypha-api
    ports:
      - "8081:8081"
    volumes:
      - ../configs/api-config.yaml:/config.yaml:Z
    command: sh -c "sleep 10 && hypha-api --config /config.yaml"
    depends_on:
      - postgres-hypha
    networks:
      - hypha-network
  
  hypha-ui:
    image: ghcr.io/hypha-rp/ui:latest
    container_name: hypha-ui
    ports:
      - "8080:80"
    volumes:
      - ../configs/nginx.conf:/etc/nginx/conf.d/default.conf:Z
    depends_on:
      - postgres-hypha
      - hypha-api
    networks:
      - hypha-network

networks:
  hypha-network:
    driver: bridge